---@class ICompost
---@field id number
---@field count number
---@field positionX number
---@field positionY number
---@field positionZ number
---@field rotationX number
---@field rotationY number
---@field rotationZ number
