---@class IFoodTrough
---@field id number
---@field count number
---@field content string
---@field positionX number
---@field positionY number
---@field positionZ number
---@field rotationX number
---@field rotationY number
---@field rotationZ number
