AddTextEntry("WEAPON_RGKNUCKLES", "red Gang knuckles")
AddTextEntry("WEAPON_BGKNUCKLES", "blue gang knuckle")
AddTextEntry("WEAPON_BLGKNUCKLES", "black gang knuckle")
AddTextEntry("WEAPON_BRGKNUCKLES", "brown gang knuckle")
AddTextEntry("WEAPON_GGKNUCKLES", "green gang knuckle")
AddTextEntry("WEAPON_GRKNUCKLES", "grey gang knuckle")
AddTextEntry("WEAPON_OGKNUCKLES", "orange gang knuckle")
AddTextEntry("WEAPON_PIKNUCKLES", "pink gang knuckle")
AddTextEntry("WEAPON_PUKNUCKLES", "purple gang knuckle")
AddTextEntry("WEAPON_WGKNUCKLES", "white gand knuckle")
AddTextEntry("WEAPON_YGKNUCKLES", "yellow gang knuckle")
AddTextEntry("WEAPON_LBGKNUCKLES", "light blue gang knuckle")
AddTextEntry("WEAPON_LGBTQGKNUCKLES", "lgbtq gang knuckle")
