Config = {}

Config.Permission = function(src, obj)
    local bl = {"unemployed", "garbage", "delivery"}
    local xPlayer = ESX.GetPlayerFromId(src)

    for k, v in pairs(bl) do 
        if xPlayer.job.name == v then 
            return false
        end 
    end
    if obj == "cone_bm" then 
        if xPlayer.job.name ~= "blackmamba" then 
            return false
        end 
    end 
    return true 
end 

Config.Objs = {

    ["cone_bm"] = {
        price = 100,
        prop = GetHashKey("prop_mp_cone_01"),
        offset = vector3(0.0, 0.8, -0.5),
        label = "Bója",
        description = "BlackMamba bója",
    },
    ["billiard"] = {
        price = 5000000,
        prop = GetHashKey("prop_pooltable_3b"),
        offset = vector3(0.0, 0.8, -0.5),
        label = "Billiárd asztal",
        description = "Egy billiárd asztal, amit a barátokkal használhatsz, KELL MELLÉ ÜTŐ IS KÜLÖN.",
    },
    ["billiarduto"] = {
        price = 5000000,
        prop = GetHashKey("prop_pool_rack_01"),
        offset = vector3(0.0, 0.8, -0.5),
        label = "Billiárd ütő",
        description = "Egy billiárd ütő, amit a barátokkal használhatsz, KELL MELLÉ ASZTAL IS KÜLÖN.",
    },
    --[[["darts"] = {
        price = 5000000,
        prop = GetHashKey("prop_dart_bd_cab_01"),
        offset = vector3(0.0, 0.8, -0.5),
        label = "Darts tábla",
        description = "Egy prémium darts tábla, tökéletes választás baráti összejövetelekhez és versengéshez. Állítsd fel a saját szórakozóhelyeden, hívd ki a barátaidat, és bizonyítsd be, ki a legpontosabb! A használathoz megfelelő hely szükséges.",
    },-]]
    ["djpult"] = {
        price = 10000000,
        prop = GetHashKey("prop_dj_deck_02"),
        offset = vector3(0.0, 0.8, -0.5),
        label = "DJ Pult",
        description = "DJ pult, hogy közösen hallgathassátok kedvenc zenéiteket.",
    },
    ["huto"] = {
        price = 70000000,
        prop = GetHashKey("prop_fridge_03"),
        offset = vector3(0.0, 0.8, -0.5),
        label = "Hűtő",
        description = "Hűtő, hogy mindenki kényelmesen tárolja ételeit, anélkül, hogy azon kéne aggódnotok, hogy gyorsan lejárnak",
    },
    ["bballgame"] = { 
        price = 70000000,
        prop = GetHashKey("pottiko"),
        offset = vector3(0.0, 0.8, -0.5),
        label = "Kosár gép",
        description = "Dobálnátok párat a spanokkal?",
    },
    ["atm"] = { 
        price = 50000000,
        prop = GetHashKey("prop_atm_01"),
        offset = vector3(0.0, 0.8, -0.5),
        label = "ATM",
        description = "Kéne KP?",
    },
    ["tv"] = { 
        price = 50000000,
        prop = GetHashKey("prop_tv_flat_01"),
        offset = vector3(0.0, 0.8, -0.5),
        label = "TV",
        description = "Néznétek közösen valamit a spanokkal?",
    },
    ["asztal"] = { 
        price = 20000000,
        prop = GetHashKey("hei_heist_din_table_07"),
        offset = vector3(0.0, 0.8, -0.5),
        label = "Asztal",
        description = "Tökéletes választás közös filmezéshez, beszélgetéshez vagy egy chill estéhez a haverokkal.",
    },
    ["chair1"] = { 
        price = 20000000,
        prop = GetHashKey("ex_mp_h_stn_chairstrip_01"),
        offset = vector3(0.0, 0.8, -0.5),
        label = "Sztriptíz szék Narancs", 
        description = "Kényelmes ülőhely egy exkluzív hangulatban.",
    },
    ["chair10"] = { 
        price = 20000000,
        prop = GetHashKey("ex_mp_h_stn_chairstrip_010"),
        offset = vector3(0.0, 0.8, -0.5),
        label = "Sztriptíz szék Barna", 
        description = "Kényelmes ülőhely egy exkluzív hangulatban.",
    },
    ["chair11"] = { 
        price = 20000000,
        prop = GetHashKey("ex_mp_h_stn_chairstrip_011"),
        offset = vector3(0.0, 0.8, -0.5),
        label = "Sztriptíz szék Fehér", 
        description = "Kényelmes ülőhely egy exkluzív hangulatban.",
    },
    ["chair7"] = { 
        price = 20000000,
        prop = GetHashKey("ex_mp_h_stn_chairstrip_07"),
        offset = vector3(0.0, 0.8, -0.5),
        label = "Sztriptíz szék Fekete", 
        description = "Kényelmes ülőhely egy exkluzív hangulatban.",
    },
    ["grill1"] = {
        price = 20000000,
        prop = GetHashKey("prop_bbq_1"),
        offset = vector3(0.0, 0.8, -0.5),
        label = "Gázgrill",
        description = "Kompakt gázgrill a gyors és hatékony sütéshez. Spanokkal egy kis kerti party?",
    },
    ["grill2"] = {
        price = 20000000,
        prop = GetHashKey("prop_bbq_2"),
        offset = vector3(0.0, 0.8, -0.5),
        label = "Kis grill",
        description = "Aprócska grill, de nagyot szól! Ideális gyors sütésekhez.",
    },
    ["grill3"] = {
        price = 20000000,
        prop = GetHashKey("prop_bbq_4_l1"),
        offset = vector3(0.0, 0.8, -0.5),
        label = "Gömbgrill",
        description = "Klasszikus gömbgrill dizájn, ami igazi BBQ hangulatot teremt.",
    },
    ["grill4"] = {
        price = 20000000,
        prop = GetHashKey("prop_bbq_5"),
        offset = vector3(0.0, 0.8, -0.5),
        label = "Gázpalackos grill",
        description = "Profibb grillezésre vágysz? Ezzel már komolyabb húsokat is megpörkölsz.",
    },
    ["grill5"] = {
        price = 20000000,
        prop = GetHashKey("prop_bbq_4"),
        offset = vector3(0.0, 0.8, -0.5),
        label = "Klasszikus grill",
        description = "Egyszerű, de nagyszerű – ez a grill tökéletes egy nyugodt sütögetéshez a haverokkal.",
    },
    ["noveny1"] = {
        price = 20000000,
        prop = GetHashKey("prop_pot_plant_05a"),
        offset = vector3(0.0, 0.8, -0.5),
        label = "Dísznövény",
        description = "Egy kis zöld növény, hogy feldobja a hangulatot és stílust csempésszen a helyszínre.",
    },
    --[[["emeloszerelo"] = {
        price = 20000000,
        prop = GetHashKey("imp_prop_impexp_post_lift"),
        offset = vector3(0.0, 0.8, -0.5),
        label = "Autóemelő",
        description = "Professzionális szerelői autóemelő, amely tökéletes választás műhelyekbe és garázsokba. Modern megjelenést és valósághű szerelői hangulatot biztosít.",
    },]]   
}

Config.AutoGovs = {
    ["police"] = {
        "N.D.A Egységeink Elindultak a Rablás Helyszínére!",
        "N.D.A Egységeink Megérkeztek a Rablás Helyszínére!",
        "Tisztelt Lakosság! A Bolt Területe 150 m-es Körzetben le van zárva! A Területet TILOS Megközelíteni és Életveszélyes! A Behatolókra Elfogató és Tűzparancs Van Kiadva!",
        "A Bent Tartózkodók Ejtettek Túszokat?",
        "A Túsztárgyaló Elindulhat Fegyvertelenül Feltett Kezekkel?",
        "A Túsztárgyaló Elindult a Bejárat Felé Feltett Kezekkel, Fegyvertelenül!",
        "Tisztelt Lakosság! A Bank Területe 250 m-es Körzetben le van zárva! A Területet TILOS Megközelíteni és Életveszélyes! A Behatolókra Elfogató és Tűzparancs van kiadva!",
        "Tisztelt Lakosság! Az Ékszerbolt Területe 150 m-es Körzetben le van zárva! A Területet TILOS Megközelíteni és Életveszélyes! A Behatolókra Elfogató és Tűzparancs van kiadva!",
        "Tisztelt Lakosság! A Nemzeti Bank területe 150 m-es Körzetben le van zárva! A Területet TILOS Megközelíteni és Életveszélyes! A Behatolókra Elfogató és Tűzparancs van kiadva!",
        "Tisztelt Lakosság! A Terület Újra Járható és Biztonságos! Köszönjük az Együttműködést!",
        "Tisztelt Polgárok! Rabszállítás indul, a Nemzeti Börtön irányába. Megkérnénk Mindenkit, Hogy ne Közelítsék meg és Végképp Ne Akadályozzák a Konvoj Haladását. A Konvoj 300 méteres körzetén tűzparancs van kiadva!",
        "Tisztelt Lakosság! A Nemzeti Börtön Területe 250 m-es Körzetben le van zárva! A Területet TILOS Megközelíteni és Életveszélyes! A Behatolókra Elfogató és Tűzparancs van kiadva!",
        "A Rabszállítás Sikeres volt! A Nemzeti Börtön Területe Újra Járható!",
        "Tisztelt Polgárok! Pénzszállítás indul, a SandyBank irányába. Megkérnénk Mindenkit, Hogy ne Közelítsék meg és Végképp Ne Akadályozzák a Konvoj Haladását. A Konvoj 300 méteres körzetén tűzparancs van kiadva!",
        "Tisztelt Lakosság! A Nemzeti Bank Területe 250 m-es Körzetben le van zárva! A Területet TILOS Megközelíteni és Életveszélyes! A Behatolókra Elfogató és Tűzparancs van kiadva!",
        "Az üldözött gépjármű álljon félre! 1. Fsz",
        "Az üldözött gépjármű álljon félre! 2. Fsz",
        "Az üldözött gépjármű álljon félre! 3. Fsz",
        "Tisztelt Lakosság! A Keleti autópályán határellenőrzés van érvényben. Az ellenőrzést figyelmen kívül hagyók, vagy azon engedély nélkül áthaladók ellen elfogató és aktív tűzparancs van érvényben.",
        "Tisztelt Lakosság! állomány nem lesz elérhető 1-órán keresztül.",
        "Tisztelt Polgárok! Fegyverszállítás indult. Megkérnénk Mindenkit, Hogy ne Közelítsék meg és Végképp Ne Akadályozzák a Konvoj Haladását. A Konvoj 300 méteres körzetén tűzparancs van kiadva!",
        "Tisztelt Lakosság! A Területe 250 m-es Körzetben le van zárva! A Területet TILOS Megközelíteni és Életveszélyes! A Behatolókra Elfogató és Tűzparancs van kiadva!",
    },
    ["fbiuj"] = {
        "FiB Egységeink Elindultak a Rablás Helyszínére!",
        "FiB Egységeink Megérkeztek a Rablás Helyszínére!",
        "Tisztelt Lakosság! A Bolt Területe 150 m-es Körzetben le van zárva! A Területet TILOS Megközelíteni és Életveszélyes! A Behatolókra Elfogató és Tűzparancs Van Kiadva!",
        "A Bent Tartózkodók Ejtettek Túszokat?",
        "A Túsztárgyaló Elindulhat Fegyvertelenül Feltett Kezekkel?",
        "A Túsztárgyaló Elindult a Bejárat Felé Feltett Kezekkel, Fegyvertelenül!",
        "Tisztelt Lakosság! A Bank Területe 250 m-es Körzetben le van zárva! A Területet TILOS Megközelíteni és Életveszélyes! A Behatolókra Elfogató és Tűzparancs van kiadva!",
        "Tisztelt Lakosság! Az Ékszerbolt Területe 150 m-es Körzetben le van zárva! A Területet TILOS Megközelíteni és Életveszélyes! A Behatolókra Elfogató és Tűzparancs van kiadva!",
        "Tisztelt Lakosság! A Nemzeti Bank területe 150 m-es Körzetben le van zárva! A Területet TILOS Megközelíteni és Életveszélyes! A Behatolókra Elfogató és Tűzparancs van kiadva!",
        "Tisztelt Lakosság! A Terület Újra Járható és Biztonságos! Köszönjük az Együttműködést!",
        "Tisztelt Polgárok! Rabszállítás indul, a Nemzeti Börtön irányába. Megkérnénk Mindenkit, Hogy ne Közelítsék meg és Végképp Ne Akadályozzák a Konvoj Haladását. A Konvoj 300 méteres körzetén tűzparancs van kiadva!",
        "Tisztelt Lakosság! A Nemzeti Börtön Területe 250 m-es Körzetben le van zárva! A Területet TILOS Megközelíteni és Életveszélyes! A Behatolókra Elfogató és Tűzparancs van kiadva!",
        "A Rabszállítás Sikeres volt! A Nemzeti Börtön Területe Újra Járható!",
        "Tisztelt Polgárok! Pénzszállítás indul, a SandyBank irányába. Megkérnénk Mindenkit, Hogy ne Közelítsék meg és Végképp Ne Akadályozzák a Konvoj Haladását. A Konvoj 300 méteres körzetén tűzparancs van kiadva!",
        "Tisztelt Lakosság! A Nemzeti Bank Területe 250 m-es Körzetben le van zárva! A Területet TILOS Megközelíteni és Életveszélyes! A Behatolókra Elfogató és Tűzparancs van kiadva!",
        "Az üldözött gépjármű álljon félre! 1. Fsz",
        "Az üldözött gépjármű álljon félre! 2. Fsz",
        "Az üldözött gépjármű álljon félre! 3. Fsz",
        "Tisztelt Lakosság! A Keleti autópályán határellenőrzés van érvényben. Az ellenőrzést figyelmen kívül hagyók, vagy azon engedély nélkül áthaladók ellen elfogató és aktív tűzparancs van érvényben.",
        "Tisztelt Lakosság! állomány nem lesz elérhető 1-órán keresztül.",
        "Tisztelt Polgárok! Fegyverszállítás indult. Megkérnénk Mindenkit, Hogy ne Közelítsék meg és Végképp Ne Akadályozzák a Konvoj Haladását. A Konvoj 300 méteres körzetén tűzparancs van kiadva!",
        "Tisztelt Lakosság! A Területe 250 m-es Körzetben le van zárva! A Területet TILOS Megközelíteni és Életveszélyes! A Behatolókra Elfogató és Tűzparancs van kiadva!",
    },
    ["uss"] = {
        "NMS Egységeink Elindultak a Rablás Helyszínére!",
        "NMS Egységeink Megérkeztek a Rablás Helyszínére!",
        "Tisztelt Lakosság! A Bolt Területe 150 m-es Körzetben le van zárva! A Területet TILOS Megközelíteni és Életveszélyes! A Behatolókra Elfogató és Tűzparancs Van Kiadva!",
        "A Bent Tartózkodók Ejtettek Túszokat?",
        "A Túsztárgyaló Elindulhat Fegyvertelenül Feltett Kezekkel?",
        "A Túsztárgyaló Elindult a Bejárat Felé Feltett Kezekkel, Fegyvertelenül!",
        "Tisztelt Lakosság! A Bank Területe 250 m-es Körzetben le van zárva! A Területet TILOS Megközelíteni és Életveszélyes! A Behatolókra Elfogató és Tűzparancs van kiadva!",
        "Tisztelt Lakosság! Az Ékszerbolt Területe 150 m-es Körzetben le van zárva! A Területet TILOS Megközelíteni és Életveszélyes! A Behatolókra Elfogató és Tűzparancs van kiadva!",
        "Tisztelt Lakosság! A Nemzeti Bank területe 150 m-es Körzetben le van zárva! A Területet TILOS Megközelíteni és Életveszélyes! A Behatolókra Elfogató és Tűzparancs van kiadva!",
        "Tisztelt Lakosság! A Terület Újra Járható és Biztonságos! Köszönjük az Együttműködést!",
        "Tisztelt Polgárok! Rabszállítás indul, a Nemzeti Börtön irányába. Megkérnénk Mindenkit, Hogy ne Közelítsék meg és Végképp Ne Akadályozzák a Konvoj Haladását. A Konvoj 300 méteres körzetén tűzparancs van kiadva!",
        "Tisztelt Lakosság! A Nemzeti Börtön Területe 250 m-es Körzetben le van zárva! A Területet TILOS Megközelíteni és Életveszélyes! A Behatolókra Elfogató és Tűzparancs van kiadva!",
        "A Rabszállítás Sikeres volt! A Nemzeti Börtön Területe Újra Járható!",
        "Tisztelt Polgárok! Pénzszállítás indul, a SandyBank irányába. Megkérnénk Mindenkit, Hogy ne Közelítsék meg és Végképp Ne Akadályozzák a Konvoj Haladását. A Konvoj 300 méteres körzetén tűzparancs van kiadva!",
        "Tisztelt Lakosság! A Nemzeti Bank Területe 250 m-es Körzetben le van zárva! A Területet TILOS Megközelíteni és Életveszélyes! A Behatolókra Elfogató és Tűzparancs van kiadva!",
        "Az üldözött gépjármű álljon félre! 1. Fsz",
        "Az üldözött gépjármű álljon félre! 2. Fsz",
        "Az üldözött gépjármű álljon félre! 3. Fsz",
        "Tisztelt Lakosság! A Keleti autópályán határellenőrzés van érvényben. Az ellenőrzést figyelmen kívül hagyók, vagy azon engedély nélkül áthaladók ellen elfogató és aktív tűzparancs van érvényben.",
        "Tisztelt Lakosság! állomány nem lesz elérhető 1-órán keresztül.",
        "Tisztelt Polgárok! Fegyverszállítás indult. Megkérnénk Mindenkit, Hogy ne Közelítsék meg és Végképp Ne Akadályozzák a Konvoj Haladását. A Konvoj 300 méteres körzetén tűzparancs van kiadva!",
        "Tisztelt Lakosság! A Területe 250 m-es Körzetben le van zárva! A Területet TILOS Megközelíteni és Életveszélyes! A Behatolókra Elfogató és Tűzparancs van kiadva!",
    },
    ["irs"] = {
        "FTA Egységeink Elindultak a Rablás Helyszínére!",
        "FTA Egységeink Megérkeztek a Rablás Helyszínére!",
        "Tisztelt Lakosság! A Bolt Területe 150 m-es Körzetben le van zárva! A Területet TILOS Megközelíteni és Életveszélyes! A Behatolókra Elfogató és Tűzparancs Van Kiadva!",
        "A Bent Tartózkodók Ejtettek Túszokat?",
        "A Túsztárgyaló Elindulhat Fegyvertelenül Feltett Kezekkel?",
        "A Túsztárgyaló Elindult a Bejárat Felé Feltett Kezekkel, Fegyvertelenül!",
        "Tisztelt Lakosság! A Bank Területe 250 m-es Körzetben le van zárva! A Területet TILOS Megközelíteni és Életveszélyes! A Behatolókra Elfogató és Tűzparancs van kiadva!",
        "Tisztelt Lakosság! Az Ékszerbolt Területe 150 m-es Körzetben le van zárva! A Területet TILOS Megközelíteni és Életveszélyes! A Behatolókra Elfogató és Tűzparancs van kiadva!",
        "Tisztelt Lakosság! A Nemzeti Bank területe 150 m-es Körzetben le van zárva! A Területet TILOS Megközelíteni és Életveszélyes! A Behatolókra Elfogató és Tűzparancs van kiadva!",
        "Tisztelt Lakosság! A Terület Újra Járható és Biztonságos! Köszönjük az Együttműködést!",
        "Tisztelt Polgárok! Rabszállítás indul, a Nemzeti Börtön irányába. Megkérnénk Mindenkit, Hogy ne Közelítsék meg és Végképp Ne Akadályozzák a Konvoj Haladását. A Konvoj 300 méteres körzetén tűzparancs van kiadva!",
        "Tisztelt Lakosság! A Nemzeti Börtön Területe 250 m-es Körzetben le van zárva! A Területet TILOS Megközelíteni és Életveszélyes! A Behatolókra Elfogató és Tűzparancs van kiadva!",
        "A Rabszállítás Sikeres volt! A Nemzeti Börtön Területe Újra Járható!",
        "Tisztelt Polgárok! Pénzszállítás indul, a SandyBank irányába. Megkérnénk Mindenkit, Hogy ne Közelítsék meg és Végképp Ne Akadályozzák a Konvoj Haladását. A Konvoj 300 méteres körzetén tűzparancs van kiadva!",
        "Tisztelt Lakosság! A Nemzeti Bank Területe 250 m-es Körzetben le van zárva! A Területet TILOS Megközelíteni és Életveszélyes! A Behatolókra Elfogató és Tűzparancs van kiadva!",
        "Az üldözött gépjármű álljon félre! 1. Fsz",
        "Az üldözött gépjármű álljon félre! 2. Fsz",
        "Az üldözött gépjármű álljon félre! 3. Fsz",
        "Tisztelt Lakosság! A Keleti autópályán határellenőrzés van érvényben. Az ellenőrzést figyelmen kívül hagyók, vagy azon engedély nélkül áthaladók ellen elfogató és aktív tűzparancs van érvényben.",
        "Tisztelt Lakosság! állomány nem lesz elérhető 1-órán keresztül.",
        "Tisztelt Polgárok! Fegyverszállítás indult. Megkérnénk Mindenkit, Hogy ne Közelítsék meg és Végképp Ne Akadályozzák a Konvoj Haladását. A Konvoj 300 méteres körzetén tűzparancs van kiadva!",
        "Tisztelt Lakosság! A Területe 250 m-es Körzetben le van zárva! A Területet TILOS Megközelíteni és Életveszélyes! A Behatolókra Elfogató és Tűzparancs van kiadva!",
    },
    ["atf"] = {
        "FEA Egységeink Elindultak a Rablás Helyszínére!",
        "FEA Egységeink Megérkeztek a Rablás Helyszínére!",
        "Tisztelt Lakosság! A Bolt Területe 150 m-es Körzetben le van zárva! A Területet TILOS Megközelíteni és Életveszélyes! A Behatolókra Elfogató és Tűzparancs Van Kiadva!",
        "A Bent Tartózkodók Ejtettek Túszokat?",
        "A Túsztárgyaló Elindulhat Fegyvertelenül Feltett Kezekkel?",
        "A Túsztárgyaló Elindult a Bejárat Felé Feltett Kezekkel, Fegyvertelenül!",
        "Tisztelt Lakosság! A Bank Területe 250 m-es Körzetben le van zárva! A Területet TILOS Megközelíteni és Életveszélyes! A Behatolókra Elfogató és Tűzparancs van kiadva!",
        "Tisztelt Lakosság! Az Ékszerbolt Területe 150 m-es Körzetben le van zárva! A Területet TILOS Megközelíteni és Életveszélyes! A Behatolókra Elfogató és Tűzparancs van kiadva!",
        "Tisztelt Lakosság! A Nemzeti Bank területe 150 m-es Körzetben le van zárva! A Területet TILOS Megközelíteni és Életveszélyes! A Behatolókra Elfogató és Tűzparancs van kiadva!",
        "Tisztelt Lakosság! A Terület Újra Járható és Biztonságos! Köszönjük az Együttműködést!",
        "Tisztelt Polgárok! Rabszállítás indul, a Nemzeti Börtön irányába. Megkérnénk Mindenkit, Hogy ne Közelítsék meg és Végképp Ne Akadályozzák a Konvoj Haladását. A Konvoj 300 méteres körzetén tűzparancs van kiadva!",
        "Tisztelt Lakosság! A Nemzeti Börtön Területe 250 m-es Körzetben le van zárva! A Területet TILOS Megközelíteni és Életveszélyes! A Behatolókra Elfogató és Tűzparancs van kiadva!",
        "A Rabszállítás Sikeres volt! A Nemzeti Börtön Területe Újra Járható!",
        "Tisztelt Polgárok! Pénzszállítás indul, a SandyBank irányába. Megkérnénk Mindenkit, Hogy ne Közelítsék meg és Végképp Ne Akadályozzák a Konvoj Haladását. A Konvoj 300 méteres körzetén tűzparancs van kiadva!",
        "Tisztelt Lakosság! A Nemzeti Bank Területe 250 m-es Körzetben le van zárva! A Területet TILOS Megközelíteni és Életveszélyes! A Behatolókra Elfogató és Tűzparancs van kiadva!",
        "Az üldözött gépjármű álljon félre! 1. Fsz",
        "Az üldözött gépjármű álljon félre! 2. Fsz",
        "Az üldözött gépjármű álljon félre! 3. Fsz",
        "Tisztelt Lakosság! A Keleti autópályán határellenőrzés van érvényben. Az ellenőrzést figyelmen kívül hagyók, vagy azon engedély nélkül áthaladók ellen elfogató és aktív tűzparancs van érvényben.",
        "Tisztelt Lakosság! állomány nem lesz elérhető 1-órán keresztül.",
        "Tisztelt Polgárok! Fegyverszállítás indult. Megkérnénk Mindenkit, Hogy ne Közelítsék meg és Végképp Ne Akadályozzák a Konvoj Haladását. A Konvoj 300 méteres körzetén tűzparancs van kiadva!",
        "Tisztelt Lakosság! A Területe 250 m-es Körzetben le van zárva! A Területet TILOS Megközelíteni és Életveszélyes! A Behatolókra Elfogató és Tűzparancs van kiadva!",
    },
    ["navi"] = {
        "USM Egységeink Elindultak a Rablás Helyszínére!",
        "USM Egységeink Megérkeztek a Rablás Helyszínére!",
        "Tisztelt Lakosság! A Bolt Területe 150 m-es Körzetben le van zárva! A Területet TILOS Megközelíteni és Életveszélyes! A Behatolókra Elfogató és Tűzparancs Van Kiadva!",
        "A Bent Tartózkodók Ejtettek Túszokat?",
        "A Túsztárgyaló Elindulhat Fegyvertelenül Feltett Kezekkel?",
        "A Túsztárgyaló Elindult a Bejárat Felé Feltett Kezekkel, Fegyvertelenül!",
        "Tisztelt Lakosság! A Bank Területe 250 m-es Körzetben le van zárva! A Területet TILOS Megközelíteni és Életveszélyes! A Behatolókra Elfogató és Tűzparancs van kiadva!",
        "Tisztelt Lakosság! Az Ékszerbolt Területe 150 m-es Körzetben le van zárva! A Területet TILOS Megközelíteni és Életveszélyes! A Behatolókra Elfogató és Tűzparancs van kiadva!",
        "Tisztelt Lakosság! A Nemzeti Bank területe 150 m-es Körzetben le van zárva! A Területet TILOS Megközelíteni és Életveszélyes! A Behatolókra Elfogató és Tűzparancs van kiadva!",
        "Tisztelt Lakosság! A Terület Újra Járható és Biztonságos! Köszönjük az Együttműködést!",
        "Tisztelt Polgárok! Rabszállítás indul, a Nemzeti Börtön irányába. Megkérnénk Mindenkit, Hogy ne Közelítsék meg és Végképp Ne Akadályozzák a Konvoj Haladását. A Konvoj 300 méteres körzetén tűzparancs van kiadva!",
        "Tisztelt Lakosság! A Nemzeti Börtön Területe 250 m-es Körzetben le van zárva! A Területet TILOS Megközelíteni és Életveszélyes! A Behatolókra Elfogató és Tűzparancs van kiadva!",
        "A Rabszállítás Sikeres volt! A Nemzeti Börtön Területe Újra Járható!",
        "Tisztelt Polgárok! Pénzszállítás indul, a SandyBank irányába. Megkérnénk Mindenkit, Hogy ne Közelítsék meg és Végképp Ne Akadályozzák a Konvoj Haladását. A Konvoj 300 méteres körzetén tűzparancs van kiadva!",
        "Tisztelt Lakosság! A Nemzeti Bank Területe 250 m-es Körzetben le van zárva! A Területet TILOS Megközelíteni és Életveszélyes! A Behatolókra Elfogató és Tűzparancs van kiadva!",
        "Az üldözött gépjármű álljon félre! 1. Fsz",
        "Az üldözött gépjármű álljon félre! 2. Fsz",
        "Az üldözött gépjármű álljon félre! 3. Fsz",
        "Tisztelt Lakosság! A Keleti autópályán határellenőrzés van érvényben. Az ellenőrzést figyelmen kívül hagyók, vagy azon engedély nélkül áthaladók ellen elfogató és aktív tűzparancs van érvényben.",
        "Tisztelt Lakosság! állomány nem lesz elérhető 1-órán keresztül.",
        "Tisztelt Polgárok! Fegyverszállítás indult. Megkérnénk Mindenkit, Hogy ne Közelítsék meg és Végképp Ne Akadályozzák a Konvoj Haladását. A Konvoj 300 méteres körzetén tűzparancs van kiadva!",
        "Tisztelt Lakosság! A Területe 250 m-es Körzetben le van zárva! A Területet TILOS Megközelíteni és Életveszélyes! A Behatolókra Elfogató és Tűzparancs van kiadva!",
    },
    ["fbi"] = {
        "CSO Egységeink Elindultak a Rablás Helyszínére!",
        "CSO Egységeink Megérkeztek a Rablás Helyszínére!",
        "Tisztelt Lakosság! A Bolt Területe 150 m-es Körzetben le van zárva! A Területet TILOS Megközelíteni és Életveszélyes! A Behatolókra Elfogató és Tűzparancs Van Kiadva!",
        "A Bent Tartózkodók Ejtettek Túszokat?",
        "A Túsztárgyaló Elindulhat Fegyvertelenül Feltett Kezekkel?",
        "A Túsztárgyaló Elindult a Bejárat Felé Feltett Kezekkel, Fegyvertelenül!",
        "Tisztelt Lakosság! A Bank Területe 250 m-es Körzetben le van zárva! A Területet TILOS Megközelíteni és Életveszélyes! A Behatolókra Elfogató és Tűzparancs van kiadva!",
        "Tisztelt Lakosság! Az Ékszerbolt Területe 150 m-es Körzetben le van zárva! A Területet TILOS Megközelíteni és Életveszélyes! A Behatolókra Elfogató és Tűzparancs van kiadva!",
        "Tisztelt Lakosság! A Nemzeti Bank területe 150 m-es Körzetben le van zárva! A Területet TILOS Megközelíteni és Életveszélyes! A Behatolókra Elfogató és Tűzparancs van kiadva!",
        "Tisztelt Lakosság! A Terület Újra Járható és Biztonságos! Köszönjük az Együttműködést!",
        "Tisztelt Polgárok! Rabszállítás indul, a Nemzeti Börtön irányába. Megkérnénk Mindenkit, Hogy ne Közelítsék meg és Végképp Ne Akadályozzák a Konvoj Haladását. A Konvoj 300 méteres körzetén tűzparancs van kiadva!",
        "Tisztelt Lakosság! A Nemzeti Börtön Területe 250 m-es Körzetben le van zárva! A Területet TILOS Megközelíteni és Életveszélyes! A Behatolókra Elfogató és Tűzparancs van kiadva!",
        "A Rabszállítás Sikeres volt! A Nemzeti Börtön Területe Újra Járható!",
        "Tisztelt Polgárok! Pénzszállítás indul, a SandyBank irányába. Megkérnénk Mindenkit, Hogy ne Közelítsék meg és Végképp Ne Akadályozzák a Konvoj Haladását. A Konvoj 300 méteres körzetén tűzparancs van kiadva!",
        "Tisztelt Lakosság! A Nemzeti Bank Területe 250 m-es Körzetben le van zárva! A Területet TILOS Megközelíteni és Életveszélyes! A Behatolókra Elfogató és Tűzparancs van kiadva!",
        "Az üldözött gépjármű álljon félre! 1. Fsz",
        "Az üldözött gépjármű álljon félre! 2. Fsz",
        "Az üldözött gépjármű álljon félre! 3. Fsz",
        "Tisztelt Lakosság! A Keleti autópályán határellenőrzés van érvényben. Az ellenőrzést figyelmen kívül hagyók, vagy azon engedély nélkül áthaladók ellen elfogató és aktív tűzparancs van érvényben.",
        "Tisztelt Lakosság! állomány nem lesz elérhető 1-órán keresztül.",
        "Tisztelt Polgárok! Fegyverszállítás indult. Megkérnénk Mindenkit, Hogy ne Közelítsék meg és Végképp Ne Akadályozzák a Konvoj Haladását. A Konvoj 300 méteres körzetén tűzparancs van kiadva!",
        "Tisztelt Lakosság! A Területe 250 m-es Körzetben le van zárva! A Területet TILOS Megközelíteni és Életveszélyes! A Behatolókra Elfogató és Tűzparancs van kiadva!",
    },
    ["detective"] = {
        "LSPD Egységeink Elindultak a Rablás Helyszínére!",
        "LSPD Egységeink Megérkeztek a Rablás Helyszínére!",
        "Tisztelt Lakosság! A Bolt Területe 150 m-es Körzetben le van zárva! A Területet TILOS Megközelíteni és Életveszélyes! A Behatolókra Elfogató és Tűzparancs Van Kiadva!",
        "A Bent Tartózkodók Ejtettek Túszokat?",
        "A Túsztárgyaló Elindulhat Fegyvertelenül Feltett Kezekkel?",
        "A Túsztárgyaló Elindult a Bejárat Felé Feltett Kezekkel, Fegyvertelenül!",
        "Tisztelt Lakosság! A Bank Területe 250 m-es Körzetben le van zárva! A Területet TILOS Megközelíteni és Életveszélyes! A Behatolókra Elfogató és Tűzparancs van kiadva!",
        "Tisztelt Lakosság! Az Ékszerbolt Területe 150 m-es Körzetben le van zárva! A Területet TILOS Megközelíteni és Életveszélyes! A Behatolókra Elfogató és Tűzparancs van kiadva!",
        "Tisztelt Lakosság! A Nemzeti Bank területe 150 m-es Körzetben le van zárva! A Területet TILOS Megközelíteni és Életveszélyes! A Behatolókra Elfogató és Tűzparancs van kiadva!",
        "Tisztelt Lakosság! A Terület Újra Járható és Biztonságos! Köszönjük az Együttműködést!",
        "Tisztelt Polgárok! Rabszállítás indul, a Nemzeti Börtön irányába. Megkérnénk Mindenkit, Hogy ne Közelítsék meg és Végképp Ne Akadályozzák a Konvoj Haladását. A Konvoj 300 méteres körzetén tűzparancs van kiadva!",
        "Tisztelt Lakosság! A Nemzeti Börtön Területe 250 m-es Körzetben le van zárva! A Területet TILOS Megközelíteni és Életveszélyes! A Behatolókra Elfogató és Tűzparancs van kiadva!",
        "A Rabszállítás Sikeres volt! A Nemzeti Börtön Területe Újra Járható!",
        "Tisztelt Polgárok! Pénzszállítás indul, a SandyBank irányába. Megkérnénk Mindenkit, Hogy ne Közelítsék meg és Végképp Ne Akadályozzák a Konvoj Haladását. A Konvoj 300 méteres körzetén tűzparancs van kiadva!",
        "Tisztelt Lakosság! A Nemzeti Bank Területe 250 m-es Körzetben le van zárva! A Területet TILOS Megközelíteni és Életveszélyes! A Behatolókra Elfogató és Tűzparancs van kiadva!",
        "Az üldözött gépjármű álljon félre! 1. Fsz",
        "Az üldözött gépjármű álljon félre! 2. Fsz",
        "Az üldözött gépjármű álljon félre! 3. Fsz",
        "Tisztelt Lakosság! A Keleti autópályán határellenőrzés van érvényben. Az ellenőrzést figyelmen kívül hagyók, vagy azon engedély nélkül áthaladók ellen elfogató és aktív tűzparancs van érvényben.",
        "Tisztelt Lakosság! állomány nem lesz elérhető 1-órán keresztül.",
        "Tisztelt Polgárok! Fegyverszállítás indult. Megkérnénk Mindenkit, Hogy ne Közelítsék meg és Végképp Ne Akadályozzák a Konvoj Haladását. A Konvoj 300 méteres körzetén tűzparancs van kiadva!",
        "Tisztelt Lakosság! A Területe 250 m-es Körzetben le van zárva! A Területet TILOS Megközelíteni és Életveszélyes! A Behatolókra Elfogató és Tűzparancs van kiadva!",
    },
    ["guardarmy"] = {
        "National Defense Unit Egységeink Elindultak a Rablás Helyszínére!",
        "National Defense Unit Egységeink Megérkeztek a Rablás Helyszínére!",
        "Tisztelt Lakosság! A Bolt Területe 150 m-es Körzetben le van zárva! A Területet TILOS Megközelíteni és Életveszélyes! A Behatolókra Elfogató és Tűzparancs Van Kiadva!",
        "A Bent Tartózkodók Ejtettek Túszokat?",
        "A Túsztárgyaló Elindulhat Fegyvertelenül Feltett Kezekkel?",
        "A Túsztárgyaló Elindult a Bejárat Felé Feltett Kezekkel, Fegyvertelenül!",
        "Tisztelt Lakosság! A Bank Területe 250 m-es Körzetben le van zárva! A Területet TILOS Megközelíteni és Életveszélyes! A Behatolókra Elfogató és Tűzparancs van kiadva!",
        "Tisztelt Lakosság! Az Ékszerbolt Területe 150 m-es Körzetben le van zárva! A Területet TILOS Megközelíteni és Életveszélyes! A Behatolókra Elfogató és Tűzparancs van kiadva!",
        "Tisztelt Lakosság! A Nemzeti Bank területe 150 m-es Körzetben le van zárva! A Területet TILOS Megközelíteni és Életveszélyes! A Behatolókra Elfogató és Tűzparancs van kiadva!",
        "Tisztelt Lakosság! A Terület Újra Járható és Biztonságos! Köszönjük az Együttműködést!",
        "Tisztelt Polgárok! Rabszállítás indul, a Nemzeti Börtön irányába. Megkérnénk Mindenkit, Hogy ne Közelítsék meg és Végképp Ne Akadályozzák a Konvoj Haladását. A Konvoj 300 méteres körzetén tűzparancs van kiadva!",
        "Tisztelt Lakosság! A Nemzeti Börtön Területe 250 m-es Körzetben le van zárva! A Területet TILOS Megközelíteni és Életveszélyes! A Behatolókra Elfogató és Tűzparancs van kiadva!",
        "A Rabszállítás Sikeres volt! A Nemzeti Börtön Területe Újra Járható!",
        "Tisztelt Polgárok! Pénzszállítás indul, a SandyBank irányába. Megkérnénk Mindenkit, Hogy ne Közelítsék meg és Végképp Ne Akadályozzák a Konvoj Haladását. A Konvoj 300 méteres körzetén tűzparancs van kiadva!",
        "Tisztelt Lakosság! A Nemzeti Bank Területe 250 m-es Körzetben le van zárva! A Területet TILOS Megközelíteni és Életveszélyes! A Behatolókra Elfogató és Tűzparancs van kiadva!",
        "Az üldözött gépjármű álljon félre! 1. Fsz",
        "Az üldözött gépjármű álljon félre! 2. Fsz",
        "Az üldözött gépjármű álljon félre! 3. Fsz",
        "Tisztelt Lakosság! A Keleti autópályán határellenőrzés van érvényben. Az ellenőrzést figyelmen kívül hagyók, vagy azon engedély nélkül áthaladók ellen elfogató és aktív tűzparancs van érvényben.",
        "Tisztelt Lakosság! állomány nem lesz elérhető 1-órán keresztül.",
        "Tisztelt Polgárok! Fegyverszállítás indult. Megkérnénk Mindenkit, Hogy ne Közelítsék meg és Végképp Ne Akadályozzák a Konvoj Haladását. A Konvoj 300 méteres körzetén tűzparancs van kiadva!",
        "Tisztelt Lakosság! A Területe 250 m-es Körzetben le van zárva! A Területet TILOS Megközelíteni és Életveszélyes! A Behatolókra Elfogató és Tűzparancs van kiadva!",
    },
    ["usms"] = {
        "TACT Egységeink Elindultak a Rablás Helyszínére!",
        "TACT Egységeink Megérkeztek a Rablás Helyszínére!",
        "Tisztelt Lakosság! A Bolt Területe 150 m-es Körzetben le van zárva! A Területet TILOS Megközelíteni és Életveszélyes! A Behatolókra Elfogató és Tűzparancs Van Kiadva!",
        "A Bent Tartózkodók Ejtettek Túszokat?",
        "A Túsztárgyaló Elindulhat Fegyvertelenül Feltett Kezekkel?",
        "A Túsztárgyaló Elindult a Bejárat Felé Feltett Kezekkel, Fegyvertelenül!",
        "Tisztelt Lakosság! A Bank Területe 250 m-es Körzetben le van zárva! A Területet TILOS Megközelíteni és Életveszélyes! A Behatolókra Elfogató és Tűzparancs van kiadva!",
        "Tisztelt Lakosság! Az Ékszerbolt Területe 150 m-es Körzetben le van zárva! A Területet TILOS Megközelíteni és Életveszélyes! A Behatolókra Elfogató és Tűzparancs van kiadva!",
        "Tisztelt Lakosság! A Nemzeti Bank területe 150 m-es Körzetben le van zárva! A Területet TILOS Megközelíteni és Életveszélyes! A Behatolókra Elfogató és Tűzparancs van kiadva!",
        "Tisztelt Lakosság! A Terület Újra Járható és Biztonságos! Köszönjük az Együttműködést!",
        "Tisztelt Polgárok! Rabszállítás indul, a Nemzeti Börtön irányába. Megkérnénk Mindenkit, Hogy ne Közelítsék meg és Végképp Ne Akadályozzák a Konvoj Haladását. A Konvoj 300 méteres körzetén tűzparancs van kiadva!",
        "Tisztelt Lakosság! A Nemzeti Börtön Területe 250 m-es Körzetben le van zárva! A Területet TILOS Megközelíteni és Életveszélyes! A Behatolókra Elfogató és Tűzparancs van kiadva!",
        "A Rabszállítás Sikeres volt! A Nemzeti Börtön Területe Újra Járható!",
        "Tisztelt Polgárok! Pénzszállítás indul, a SandyBank irányába. Megkérnénk Mindenkit, Hogy ne Közelítsék meg és Végképp Ne Akadályozzák a Konvoj Haladását. A Konvoj 300 méteres körzetén tűzparancs van kiadva!",
        "Tisztelt Lakosság! A Nemzeti Bank Területe 250 m-es Körzetben le van zárva! A Területet TILOS Megközelíteni és Életveszélyes! A Behatolókra Elfogató és Tűzparancs van kiadva!",
        "Az üldözött gépjármű álljon félre! 1. Fsz",
        "Az üldözött gépjármű álljon félre! 2. Fsz",
        "Az üldözött gépjármű álljon félre! 3. Fsz",
        "Tisztelt Lakosság! A Keleti autópályán határellenőrzés van érvényben. Az ellenőrzést figyelmen kívül hagyók, vagy azon engedély nélkül áthaladók ellen elfogató és aktív tűzparancs van érvényben.",
        "Tisztelt Lakosság! állomány nem lesz elérhető 1-órán keresztül.",
        "Tisztelt Polgárok! Fegyverszállítás indult. Megkérnénk Mindenkit, Hogy ne Közelítsék meg és Végképp Ne Akadályozzák a Konvoj Haladását. A Konvoj 300 méteres körzetén tűzparancs van kiadva!",
        "Tisztelt Lakosság! A Területe 250 m-es Körzetben le van zárva! A Területet TILOS Megközelíteni és Életveszélyes! A Behatolókra Elfogató és Tűzparancs van kiadva!",
    },
    ["servicess"] = {
        "SNSS Egységeink Elindultak a Rablás Helyszínére!",
        "SNSS Egységeink Megérkeztek a Rablás Helyszínére!",
        "Tisztelt Lakosság! A Bolt Területe 150 m-es Körzetben le van zárva! A Területet TILOS Megközelíteni és Életveszélyes! A Behatolókra Elfogató és Tűzparancs Van Kiadva!",
        "A Bent Tartózkodók Ejtettek Túszokat?",
        "A Túsztárgyaló Elindulhat Fegyvertelenül Feltett Kezekkel?",
        "A Túsztárgyaló Elindult a Bejárat Felé Feltett Kezekkel, Fegyvertelenül!",
        "Tisztelt Lakosság! A Bank Területe 250 m-es Körzetben le van zárva! A Területet TILOS Megközelíteni és Életveszélyes! A Behatolókra Elfogató és Tűzparancs van kiadva!",
        "Tisztelt Lakosság! Az Ékszerbolt Területe 150 m-es Körzetben le van zárva! A Területet TILOS Megközelíteni és Életveszélyes! A Behatolókra Elfogató és Tűzparancs van kiadva!",
        "Tisztelt Lakosság! A Nemzeti Bank területe 150 m-es Körzetben le van zárva! A Területet TILOS Megközelíteni és Életveszélyes! A Behatolókra Elfogató és Tűzparancs van kiadva!",
        "Tisztelt Lakosság! A Terület Újra Járható és Biztonságos! Köszönjük az Együttműködést!",
        "Tisztelt Polgárok! Rabszállítás indul, a Nemzeti Börtön irányába. Megkérnénk Mindenkit, Hogy ne Közelítsék meg és Végképp Ne Akadályozzák a Konvoj Haladását. A Konvoj 300 méteres körzetén tűzparancs van kiadva!",
        "Tisztelt Lakosság! A Nemzeti Börtön Területe 250 m-es Körzetben le van zárva! A Területet TILOS Megközelíteni és Életveszélyes! A Behatolókra Elfogató és Tűzparancs van kiadva!",
        "A Rabszállítás Sikeres volt! A Nemzeti Börtön Területe Újra Járható!",
        "Tisztelt Polgárok! Pénzszállítás indul, a SandyBank irányába. Megkérnénk Mindenkit, Hogy ne Közelítsék meg és Végképp Ne Akadályozzák a Konvoj Haladását. A Konvoj 300 méteres körzetén tűzparancs van kiadva!",
        "Tisztelt Lakosság! A Nemzeti Bank Területe 250 m-es Körzetben le van zárva! A Területet TILOS Megközelíteni és Életveszélyes! A Behatolókra Elfogató és Tűzparancs van kiadva!",
        "Az üldözött gépjármű álljon félre! 1. Fsz",
        "Az üldözött gépjármű álljon félre! 2. Fsz",
        "Az üldözött gépjármű álljon félre! 3. Fsz",
        "Tisztelt Lakosság! A Keleti autópályán határellenőrzés van érvényben. Az ellenőrzést figyelmen kívül hagyók, vagy azon engedély nélkül áthaladók ellen elfogató és aktív tűzparancs van érvényben.",
        "Tisztelt Lakosság! állomány nem lesz elérhető 1-órán keresztül.",
        "Tisztelt Polgárok! Fegyverszállítás indult. Megkérnénk Mindenkit, Hogy ne Közelítsék meg és Végképp Ne Akadályozzák a Konvoj Haladását. A Konvoj 300 méteres körzetén tűzparancs van kiadva!",
        "Tisztelt Lakosság! A Területe 250 m-es Körzetben le van zárva! A Területet TILOS Megközelíteni és Életveszélyes! A Behatolókra Elfogató és Tűzparancs van kiadva!",
    },
}