AddTextEntry("WEAPON_MK2NICO", "mk2nico")
AddTextEntry("WEAPON_HKG3A3", "HKG3A3")
AddTextEntry("WEAPON_HKG3A3", "RGX")
AddTextEntry("WEAPON_999AP", "999 AP")
AddTextEntry("WEAPON_1441", "1141 Pistol")
AddTextEntry("WEAPON_BEANBAGSHOTGUN", "BEANBAGSHOTGUN")
AddTextEntry("WEAPON_BLOCKAP", "BlockAP")
AddTextEntry("WEAPON_BLOCK_MUSKET", "Block Musketa")
AddTextEntry("WEAPON_DURANDA_AP", "Duranda AP")
AddTextEntry("WEAPON_DURANDAPISTOL", "Duranda Pisztoly")
AddTextEntry("WEAPON_GHOSTAP", "GhostAP")
AddTextEntry("WEAPON_GHOSTGLOCK", "Ghost Glock")
AddTextEntry("WEAPON_PISTOL_999", "Pistol999")
AddTextEntry("WEAPON_VICTUSXMR", "Victus XMR")
AddTextEntry("WEAPON_VICTUSXMR", "Victus XMR")
AddTextEntry("WEAPON_fn57", "Fnseven")