-- This resource was generated by grzyClothTool :)
-- https://discord.gg/HCQutNhxWt

fx_version 'cerulean'
game 'gta5'
author 'Visual'

files {
    'mp_m_freemode_01_bcujegyedi2.meta',
    'mp_f_freemode_01_bcujegyedi2.meta'
}

data_file 'SHOP_PED_APPAREL_META_FILE' 'mp_m_freemode_01_bcujegyedi2.meta'
data_file 'SHOP_PED_APPAREL_META_FILE' 'mp_f_freemode_01_bcujegyedi2.meta'
