Config = {}

Config.NPC = {model = GetHashKey('a_m_y_business_02'), coords = vector4(-296.2818, 6136.5083, 30.465337, 228.515), label = "[Efraim]~n~Fegyver craft"}


Config.Items = {
    ['WEAPON_67_G17GRIP'] = {name = 'G67 G17GRIP', amount = 1, items = {
        {name = "67g17cso", label = "67G17 cső (Egyedi)", amount = 1},
        {name = "67g17ravasz", label = "67G17 ravasz (Egyedi)", amount = 1},
        {name = "67g17tar", label = "67G17 tár (Egyedi)", amount = 1},
        {name = "steel", label = "Acél", amount = 40},
        {name = "iron", label = "Vas", amount = 40},
        {name = "copper", label = "Réz", amount = 40},
        {name = "money", label = "Pénz", amount = 2000000},
    }},
    ['WEAPON_ELK_G17'] = {name = 'ELK G17', amount = 1, items = {
        {name = "elkg17cso", label = "elkg17 cső (Egyedi)", amount = 1},
        {name = "elkg17ravas", label = "elkg17 ravasz (Egyedi)", amount = 1},
        {name = "elkg17tar", label = "elkg17 tár (Egyedi)", amount = 1},
        {name = "steel", label = "Acél", amount = 40},
        {name = "iron", label = "Vas", amount = 40},
        {name = "copper", label = "Réz", amount = 40},
        {name = "money", label = "Pénz", amount = 2000000},
    }},
    ['WEAPON_M47V2'] = {name = 'M47V2', amount = 1, items = {
        {name = "m47valtamasz", label = "M47 válltámasz (Egyedi)", amount = 1},
        {name = "m47tar", label = "M47 tár (Egyedi)", amount = 1},
        {name = "m47ravasz", label = "M47 ravasz (Egyedi)", amount = 1},
        {name = "m47cso", label = "M47 cső (Egyedi)", amount = 1},
        {name = "m47belso", label = "M47 belsőszerkezet (Egyedi)", amount = 1},
        {name = "steel", label = "Acél", amount = 40},
        {name = "iron", label = "Vas", amount = 40},
        {name = "copper", label = "Réz", amount = 40},
        {name = "money", label = "Pénz", amount = 2000000},
    }},
    ['WEAPON_MACHINE_PISTOL_RED_CHR'] = {name = 'Machine Pistol Red CHR', amount = 1, items = {
        {name = "machinepistolredvaltamasz", label = "Machine válltámasz (Egyedi)", amount = 1},
        {name = "machinepistolredtar", label = "Machine tár (Egyedi)", amount = 1},
        {name = "machinepistolredravasz", label = "Machine ravasz (Egyedi)", amount = 1},
        {name = "machinepistolredcso", label = "Machine cső (Egyedi)", amount = 1},
        {name = "steel", label = "Acél", amount = 40},
        {name = "iron", label = "Vas", amount = 40},
        {name = "copper", label = "Réz", amount = 40},
        {name = "money", label = "Pénz", amount = 2000000},
    }},
    ['WEAPON_TWAN_G17'] = {name = 'Twan G17', amount = 1, items = {
        {name = "wang17cso", label = "Twang G17 Cső (Egyedi)", amount = 1},
        {name = "wang17ravasz", label = "Twang G17 Ravasz (Egyedi)", amount = 1},
        {name = "wang17tar", label = "Twang G17 Tár (Egyedi)", amount = 1},
        {name = "steel", label = "Acél", amount = 40},
        {name = "iron", label = "Vas", amount = 40},
        {name = "copper", label = "Réz", amount = 40},
        {name = "money", label = "Pénz", amount = 2000000},
    }},
    ['WEAPON_CXP77'] = {name = 'CXP77', amount = 1, items = {
        {name = "cxp77cso", label = "CXP77 Cső (Egyedi)", amount = 1},
        {name = "cxp77hang", label = "CXP77 Hang (Egyedi)", amount = 1},
        {name = "cxp77tar", label = "CXP77 Tár (Egyedi)", amount = 1},
        {name = "steel", label = "Acél", amount = 40},
        {name = "iron", label = "Vas", amount = 40},
        {name = "copper", label = "Réz", amount = 40},
        {name = "money", label = "Pénz", amount = 2000000},
    }},
    ['WEAPON_GLOCKYUN'] = {name = 'Glockyun', amount = 1, items = {
        {name = "glockyuncso", label = "Glockyun Cső (Egyedi)", amount = 1},
        {name = "glockyunmarkol", label = "Glockyun Markolat (Egyedi)", amount = 1},
        {name = "glockyuntar", label = "Glockyun Tár (Egyedi)", amount = 1},
        {name = "steel", label = "Acél", amount = 40},
        {name = "iron", label = "Vas", amount = 40},
        {name = "copper", label = "Réz", amount = 40},
        {name = "money", label = "Pénz", amount = 2000000},
    }},
    ['WEAPON_GK17_LUMINA'] = {name = 'WhiteAP', amount = 1, items = {
        {name = "whiteaptar", label = "WhiteAP Tár (Egyedi)", amount = 1},
        {name = "whiteapcso", label = "WhiteAP Cső (Egyedi)", amount = 1},
        {name = "whiteapmarkolat", label = "WhiteAP Markolat (Egyedi)", amount = 1},
        {name = "steel", label = "Acél", amount = 40},
        {name = "iron", label = "Vas", amount = 40},
        {name = "copper", label = "Réz", amount = 40},
        {name = "money", label = "Pénz", amount = 2000000},
    }},
    ['WEAPON_SKY_PISTOL'] = {name = 'Sky Pistol', amount = 1, items = {
        {name = "skycso", label = "Sky Cső (Egyedi)", amount = 1},
        {name = "skyhatso", label = "Sky Hátsó (Egyedi)", amount = 1},
        {name = "skymarkolat", label = "Sky Markolat (Egyedi)", amount = 1},
        {name = "steel", label = "Acél", amount = 40},
        {name = "iron", label = "Vas", amount = 40},
        {name = "copper", label = "Réz", amount = 40},
        {name = "money", label = "Pénz", amount = 2000000},
    }},
    ['WEAPON_XV3_HOLY_WIRE'] = {name = 'XV3 Holy Wire', amount = 1, items = {
        {name = "xv3cso", label = "XV3 Cső (Egyedi)", amount = 1},
        {name = "xv3markolat", label = "XV3 Markolat (Egyedi)", amount = 1},
        {name = "xv3tar", label = "XV3 Tár (Egyedi)", amount = 1},
        {name = "steel", label = "Acél", amount = 40},
        {name = "iron", label = "Vas", amount = 40},
        {name = "copper", label = "Réz", amount = 40},
        {name = "money", label = "Pénz", amount = 2000000},
    }},
    ['WEAPON_DEVILSWITCH'] = {name = 'DEVILSWITCH', amount = 1, items = {
        {name = "devilswitchcso", label = "Devilswitch Cső (Egyedi)", amount = 1},
        {name = "devilswitchmarkolat", label = "Devilswitch Markolat (Egyedi)", amount = 1},
        {name = "devilswitchtar", label = "Devilswitch Tár (Egyedi)", amount = 1},
        {name = "devilswitchlampa", label = "Devilswitch Lámpa (Egyedi)", amount = 1},
        {name = "steel", label = "Acél", amount = 40},
        {name = "iron", label = "Vas", amount = 40},
        {name = "copper", label = "Réz", amount = 40},
        {name = "money", label = "Pénz", amount = 2000000},
    }},
    ['WEAPON_GK18_BLACKGOLD'] = {name = 'GK18 BlackGold', amount = 1, items = {
        {name = "blackgoldcso", label = "BlackGold Cső (Egyedi)", amount = 1},
        {name = "blackgoldmarkolat", label = "BlackGold Markolat (Egyedi)", amount = 1},
        {name = "blackgolddobtar", label = "BlackGold Dobtár (Egyedi)", amount = 1},
        {name = "blackgoldhang", label = "BlackGold Hangtompító (Egyedi)", amount = 1},
        {name = "steel", label = "Acél", amount = 40},
        {name = "iron", label = "Vas", amount = 40},
        {name = "copper", label = "Réz", amount = 40},
        {name = "money", label = "Pénz", amount = 2000000},
    }},
    ['WEAPON_GK20_BIOHAZARD'] = {name = 'GK20 Biohazard', amount = 1, items = {
        {name = "biohazardcso", label = "Biohazard Cső (Egyedi)", amount = 1},
        {name = "biohazardmarkolat", label = "Biohazard Markolat (Egyedi)", amount = 1},
        {name = "biohazardtar", label = "Biohazard Tár (Egyedi)", amount = 1},
        {name = "biohazardkomp", label = "Biohazard Kompenzátor (Egyedi)", amount = 1},
        {name = "steel", label = "Acél", amount = 40},
        {name = "iron", label = "Vas", amount = 40},
        {name = "copper", label = "Réz", amount = 40},
        {name = "money", label = "Pénz", amount = 2000000},
    }},
    ['WEAPON_LUCKY_G19X'] = {name = 'Lucky G19X', amount = 1, items = {
        {name = "luckyg19xcso", label = "Lucky G19X Cső (Egyedi)", amount = 1},
        {name = "luckyg19xegesz", label = "Lucky G19X Egész (Egyedi)", amount = 1},
        {name = "luckyg19xtar", label = "Lucky G19X Tár (Egyedi)", amount = 1},
        {name = "steel", label = "Acél", amount = 40},
        {name = "iron", label = "Vas", amount = 40},
        {name = "copper", label = "Réz", amount = 40},
        {name = "money", label = "Pénz", amount = 2000000},
    }},
    ['WEAPON_CRACKN_G20'] = {name = 'CrackNG20', amount = 1, items = {
        {name = "crackng20cso", label = "CrackNG20 Cső (Egyedi)", amount = 1},
        {name = "crackng20egesz", label = "CrackNG20 Egész (Egyedi)", amount = 1},
        {name = "crackng20vaz", label = "CrackNG20 Váz (Egyedi)", amount = 1},
        {name = "steel", label = "Acél", amount = 40},
        {name = "iron", label = "Vas", amount = 40},
        {name = "copper", label = "Réz", amount = 40},
        {name = "money", label = "Pénz", amount = 2000000},
    }},
    ['WEAPON_CRIM_G17'] = {name = 'Crim G17', amount = 1, items = {
        {name = "crimg17egesz", label = "Crim G17 Egész (Egyedi)", amount = 1},
        {name = "crimg17scoop", label = "Crim G17 Scoop (Egyedi)", amount = 1},
        {name = "crimg17tar", label = "Crim G17 Tár (Egyedi)", amount = 1},
        {name = "steel", label = "Acél", amount = 40},
        {name = "iron", label = "Vas", amount = 40},
        {name = "copper", label = "Réz", amount = 40},
        {name = "money", label = "Pénz", amount = 2000000},
    }},
    ['WEAPON_GLUE_GUN'] = {name = 'Glue Gun', amount = 1, items = {
        {name = "gluegunegesz", label = "Glue Gun Egész (Egyedi)", amount = 1},
        {name = "gluegunravaz", label = "Glue Gun Ravasz (Egyedi)", amount = 1},
        {name = "gluegunscoop", label = "Glue Gun Scoop (Egyedi)", amount = 1},
        {name = "steel", label = "Acél", amount = 40},
        {name = "iron", label = "Vas", amount = 40},
        {name = "copper", label = "Réz", amount = 40},
        {name = "money", label = "Pénz", amount = 2000000},
    }},
    ['WEAPON_GLDXN'] = {name = 'Pusztító GLDXN', amount = 1, items = {
        {name = "gldxnvaz", label = "Pusztító Váz (Egyedi)", amount = 1},
        {name = "gldxnvazscoop", label = "Pusztító Scope (Egyedi)", amount = 1},
        {name = "gldxnvazcso", label = "Pusztító Cső (Egyedi)", amount = 1},
        {name = "steel", label = "Acél", amount = 40},
        {name = "iron", label = "Vas", amount = 40},
        {name = "copper", label = "Réz", amount = 40},
        {name = "money", label = "Pénz", amount = 2000000},
    }},
    ['WEAPON_999AP'] = {name = '999 AP', amount = 1, items = {
        {name = "999apcso", label = "999AP Cso (Egyedi)", amount = 1},
        {name = "999aptar", label = "999AP Tár (Egyedi)", amount = 1},
        {name = "999apravasz", label = "999AP Ravasz (Egyedi)", amount = 1},
        {name = "steel", label = "Acél", amount = 40},
        {name = "iron", label = "Vas", amount = 40},
        {name = "copper", label = "Réz", amount = 40},
        {name = "money", label = "Pénz", amount = 2000000},
    }},
    ['WEAPON_PISTOL_999'] = {name = '999 Pistol', amount = 1, items = {
        {name = "999tar", label = "999 Tár (Egyedi)", amount = 1},
        {name = "999cso", label = "999 Cső (Egyedi)", amount = 1},
        {name = "999ravasz", label = "999 Ravasz (Egyedi)", amount = 1},
        {name = "steel", label = "Acél", amount = 40},
        {name = "iron", label = "Vas", amount = 40},
        {name = "copper", label = "Réz", amount = 40},
        {name = "money", label = "Pénz", amount = 2000000},
    }},
    ['WEAPON_1441'] = {name = '1441', amount = 1, items = {
        {name = "1441pistolravasz", label = "1441 Ravasz (Egyedi)", amount = 1},
        {name = "1441pistolcso", label = "1441 Cső (Egyedi)", amount = 1},
        {name = "1441pistoltar", label = "1441 Tár (Egyedi)", amount = 1},
        {name = "steel", label = "Acél", amount = 40},
        {name = "iron", label = "Vas", amount = 40},
        {name = "copper", label = "Réz", amount = 40},
        {name = "money", label = "Pénz", amount = 2000000},
    }},
    ['WEAPON_BLOCKAP'] = {name = 'Block AP', amount = 1, items = {
        {name = "blockcso", label = "Block Cső (Egyedi)", amount = 1},
        {name = "blocktar", label = "Block Tár (Egyedi)", amount = 1},
        {name = "blockravasz", label = "Block Ravasz (Egyedi)", amount = 1},
        {name = "steel", label = "Acél", amount = 40},
        {name = "iron", label = "Vas", amount = 40},
        {name = "copper", label = "Réz", amount = 40},
        {name = "money", label = "Pénz", amount = 2000000},
    }},
    ['WEAPON_VICTUSXMR'] = {name = 'Victus XMR', amount = 1, items = {
        {name = "VICTUScso", label = "Victus Cső (Egyedi)", amount = 1},
        {name = "VICTUStar", label = "Victus Tár (Egyedi)", amount = 1},
        {name = "VICTUSbelsoszerkezet", label = "Victus Belső Szerkezet (Egyedi)", amount = 1},
        {name = "VICTUStavcso", label = "Victus Távcső (Egyedi)", amount = 1},
        {name = "steel", label = "Acél", amount = 40},
        {name = "iron", label = "Vas", amount = 40},
        {name = "copper", label = "Réz", amount = 40},
        {name = "money", label = "Pénz", amount = 2000000},
    }},
    ['WEAPON_BLOCK_MUSKET'] = {name = 'Block Musket', amount = 1, items = {
        {name = "blockmusketbelso", label = "Block Musket Belső (Egyedi)", amount = 1},
        {name = "blockmusketcso", label = "Block Musket Cső (Egyedi)", amount = 1},
        {name = "blockmusketravasz", label = "Block Musket Ravasz (Egyedi)", amount = 1},
        {name = "blockmuskettar", label = "Block Musket Tár (Egyedi)", amount = 1},
        {name = "blockmusketvaltamasz", label = "Block Musket Válltámasz (Egyedi)", amount = 1},
        {name = "steel", label = "Acél", amount = 40},
        {name = "iron", label = "Vas", amount = 40},
        {name = "copper", label = "Réz", amount = 40},
        {name = "money", label = "Pénz", amount = 2000000},
    }},
    ['WEAPON_GYS'] = {name = 'GYS', amount = 1, items = {
        {name = "gyscso", label = "GYS Cső (Egyedi)", amount = 1},
        {name = "gysravasz", label = "GYS Ravasz (Egyedi)", amount = 1},
        {name = "gystar", label = "GYS Tár (Egyedi)", amount = 1},
        {name = "gysvaltamasz", label = "GYS Válltámasz (Egyedi)", amount = 1},
        {name = "steel", label = "Acél", amount = 40},
        {name = "iron", label = "Vas", amount = 40},
        {name = "copper", label = "Réz", amount = 40},
        {name = "money", label = "Pénz", amount = 2000000},
    }},
    ['WEAPON_M9_P_CHROMIUM'] = {name = 'M9 P Chromium', amount = 1, items = {
        {name = "m9pchromiumtar", label = "M9 Chromium Tár (Egyedi)", amount = 1},
        {name = "m9pchromiumcso", label = "M9 Chromium Cső (Egyedi)", amount = 1},
        {name = "m9pchromiumvaltamasz", label = "M9 Chromium Válltámasz (Egyedi)", amount = 1},
        {name = "m9pchromiumravasz", label = "M9 Chromium Ravasz (Egyedi)", amount = 1},
        {name = "steel", label = "Acél", amount = 40},
        {name = "iron", label = "Vas", amount = 40},
        {name = "copper", label = "Réz", amount = 40},
        {name = "money", label = "Pénz", amount = 2000000},
    }},
    ['WEAPON_DURANDAPISTOL'] = {name = 'Duranda Pistol', amount = 1, items = {
        {name = "duranda2ravasz", label = "Duranda Ravasz (Egyedi)", amount = 1},
        {name = "duranda2cso", label = "Duranda Cső (Egyedi)", amount = 1},
        {name = "duranda2tar", label = "Duranda Tár (Egyedi)", amount = 1},
        {name = "steel", label = "Acél", amount = 40},
        {name = "iron", label = "Vas", amount = 40},
        {name = "copper", label = "Réz", amount = 40},
        {name = "money", label = "Pénz", amount = 2000000},
    }},
    ['WEAPON_THERMALKATANAS'] = {name = 'Katana', amount = 1, items = {
        {name = "steel", label = "Acél", amount = 100},
        {name = "iron", label = "Vas", amount = 100},
        {name = "copper", label = "Réz", amount = 100},
        {name = "money", label = "Pénz", amount = 2000000},
    }},
    ['aranycsakany'] = {name = 'Arany Csákány', amount = 1, items = {
        {name = "steel", label = "Acél", amount = 10},
        {name = "iron", label = "Vas", amount = 10},
        {name = "copper", label = "Réz", amount = 10},
    }},
}