AddTextEntry("WEAPON_BLUE_STEEL_KNIFE", "Blue Steel")
AddTextEntry("WEAPON_CASE_HARDENED_KNIFE", "Case Hardened")
AddTextEntry("WEAPON_CRIMSON_WEB_KNIFE", "Crimson Web")
AddTextEntry("WEAPON_FADE_KNIFE", "Fade")
AddTextEntry("WEAPON_FOREST_DDPAT_KNIFE", "Forest DDPAT")
AddTextEntry("WEAPON_SAFARI_MESH_KNIFE", "Safari Mesh")
AddTextEntry("WEAPON_SCORCHED_KNIFE", "Scorched")
AddTextEntry("WEAPON_SLAUGHTER_KNIFE", "Slaughter")
AddTextEntry("WEAPON_STAINED_KNIFE", "Stained")
AddTextEntry("WEAPON_URBAN_MASKED_KNIFE", "Urban Masked")
AddTextEntry("WEAPON_VANILLA_KNIFE", "Vanilla")