Recipes = {
    ["weapon_machinepistol"] = {
        false, "tec9belso", "tec9cso",
        false, "tec9tar", false,
        "veresrejtelyeslevel", "recipe_tech", false,
    },
    ["weapon_pistol"] = {
        false, "pistolbelso", "pistolcso",
        false, "pistoltar", "recipe_pistol",
        "veresrejtelyeslevel", false, false,
    },
    ["weapon_fn57"] = {
        false, "fnsevetar", "fnsevecso",
        false, "fnsevebelso", "recipe_pistol",
        "veresrejtelyeslevel", false, false,
    },
    ["weapon_assaultrifle"] = {
        false, "veresrejtelyeslevel", "ak47cso",
        false, "ak47belso", "ak47ravasz",
        "ak47valtamasz", "ak47tar", "recipe_rfile",
    },
    ["weapon_pumpshotgun"] = {
        false, "veresrejtelyeslevel", "shotguncso",
        false, "shotgunbelso", "shotgunravasz",
        "shotgunvaltamasz", "shotguntar", false,
    },
    ["weapon_microsmg"] = {
        false, "vizbenazottlevel", "uzicso",
        false, "uzibelso", "uziravasz",
        "recipe_micro", "uzitar", false,
    },
    ["weapon_appistol"] = {
        "aptar", false, "apmarkolat",
        "apravasz", "vizbenazottlevel", false,
        "apvaz", "recipe_appistol", false,
    },
    ["apmarkolat"] = {
        false, false, "steel",
        false, "copper", false,
        false, false, "iron",
    },
    ["apravasz"] = {
        false, "iron", "steel",
        false, false, false,
        false, false, "copper",
    },
    ["apvaz"] = {
        "steel", "iron", false,
        false, false, false,
        false, "copper", false,
    },
    ["aptar"] = {
        false, "iron", "copper",
        false, "steel", false,
        false, false, false,
    },
    ["tec9belso"] = {
        false, false, false,
        false, false, false,
        "steel", "copper", "iron",
    },
    ["tec9cso"] = {
        false, false, false,
        false, false, false,
        "iron", "steel", "copper",
    },
    ["tec9tar"] = {
        false, "iron", false,
        false, "steel", false,
        false, "copper", false,
    },
    ["pistolbelso"] = {
        "iron", false, false,
        false, "steel", false,
        false, "copper", false,
    },
    ["pistolcso"] = {
        false, false, "iron",
        false, "steel", false,
        false, "copper", false,
    },
    ["pistoltar"] = {
        false, "iron", false,
        false, "steel", false,
        "copper", false, false,
    },

    ["weapon_vintagepistol"] = {
        false, "vizbenazottlevel", "vimarkolat",
        false, "viravasz", "vitar",
        "vivaz", false, false,
    },
    ["vimarkolat"] = {
        "iron", false, false,
        "steel", false, false,
        "copper", false, false,
    },
    ["viravasz"] = {
        "iron", false, false,
        "copper", false, false,
        "steel", false, false,
    },
    ["vitar"] = {
        "copper", false, false,
        "iron", false, false,
        "steel", false, false,
    },
    ["vivaz"] = {
        "copper", false, false,
        "steel", false, false,
        "iron", false, false,
    },

    ["weapon_combatpdw"] = {
        false, false, "cbcso",
        "vizbenazottlevel", "cbmarkolat", "cbrravasz",
        "cbtarto", false, false,
    },
    ["cbcso"] = {
        false, false, "iron",
        false, false, "copper",
        false, false, "steel",
    },
    ["cbmarkolat"] = {
        false, false, "copper",
        false, false, "iron",
        false, false, "steel",
    },
    ["cbrravasz"] = {
        false, false, "copper",
        false, false, "steel",
        false, false, "iron",
    },
    ["cbtarto"] = {
        false, false, "steel",
        false, false, "copper",
        false, false, "iron",
    },
}

WEAPONPRICE = 2500000

KeepItems = {
    ["weapon_machinepistol"] = {
        false, false, false,
        false, false, false,
        false, false, false,
    },
    ["weapon_pistol"] = {
        false, false, false,
        false, false, false,
        false, false, false,
    },
    ["weapon_assaultrifle"] = {
        false, false, false,
        false, false, false,
        false, false, false,
    },
    ["weapon_pumpshotgun"] = {
        false, false, false,
        false, false, false,
        false, false, false,
    },
    ["weapon_microsmg"] = {
        false, false, false,
        false, false, false,
        false, false, false,
    },
    ["weapon_appistol"] = {
        false, false, false,
        false, false, false,
        false, false, false,
    },
    ["apmarkolat"] = {
        false, false, false,
        false, false, false,
        false, false, false,
    },
    ["apravasz"] = {
        false, false, false,
        false, false, false,
        false, false, false,
    },
    ["apvaz"] = {
        false, false, false,
        false, false, false,
        false, false, false,
    },
    ["aptar"] = {
        false, false, false,
        false, false, false,
        false, false, false,
    },
    ["tec9belso"] = {
        false, false, false,
        false, false, false,
        false, false, false,
    },
    ["tec9cso"] = {
        false, false, false,
        false, false, false,
        false, false, false,
    },
    ["tec9tar"] = {
        false, false, false,
        false, false, false,
        false, false, false,
    },
    ["weapon_vintagepistol"] = {
        false, false, false,
        false, false, false,
        false, false, false,
    },
    ["vimarkolat"] = {
        false, false, false,
        false, false, false,
        false, false, false,
    },
    ["viravasz"] = {
        false, false, false,
        false, false, false,
        false, false, false,
    },
    ["vitar"] = {
        false, false, false,
        false, false, false,
        false, false, false,
    },
    ["vivaz"] = {
        false, false, false,
        false, false, false,
        false, false, false,
    },
    ["weapon_combatpdw"] = {
        false, false, false,
        false, false, false,
        false, false, false,
    },
    ["cbcso"] = {
        false, false, false,
        false, false, false,
        false, false, false,
    },
    ["cbmarkolat"] = {
        false, false, false,
        false, false, false,
        false, false, false,
    },
    ["cbrravasz"] = {
        false, false, false,
        false, false, false,
        false, false, false,
    },
    ["cbtarto"] = {
        false, false, false,
        false, false, false,
        false, false, false,
    },
    ["pistolbelso"] = {
        false, false, false,
        false, false, false,
        false, false, false,
    },
    ["pistolcso"] = {
        false, false, false,
        false, false, false,
        false, false, false,
    },
    ["pistoltar"] = {
        false, false, false,
        false, false, false,
        false, false, false,
    },
}

RecipeRewards = {
    ["weapon_pistol"] = 1,
    ["weapon_machinepistol"] = 1,
    ["weapon_assaultrifle"] = 1,
    ["weapon_pumpshotgun"] = 1,
    ["weapon_microsmg"] = 1,
    ["weapon_appistol"] = 1,
    ["apmarkolat"] = 4,
    ["apravasz"] = 4,
    ["apvaz"] = 4,
    ["aptar"] = 4,
    ["tec9belso"] = 4,
    ["tec9cso"] = 4,
    ["tec9tar"] = 4,
    ["weapon_vintagepistol"] = 1,
    ["vimarkolat"] = 4,
    ["viravasz"] = 4,
    ["vitar"] = 4,
    ["vivaz"] = 4,
    ["weapon_combatpdw"] = 1,
    ["cbcso"] = 4,
    ["cbmarkolat"] = 4,
    ["cbrravasz"] = 4,
    ["cbtarto"] = 4,
    ["pistolbelso"] = 4,
    ["pistolcso"] = 4,
    ["pistoltar"] = 4,
}

CraftTime = {
    ["weapon_pistol"] = 60.0,
    ["weapon_machinepistol"] = 60.0,
    ["weapon_assaultrifle"] = 60.0,
    ["weapon_pumpshotgun"] = 60.0,
    ["weapon_microsmg"] = 60.0,
    ["weapon_appistol"] = 60.0,
    ["apmarkolat"] = 60.0,
    ["apravasz"] = 60.0,
    ["apvaz"] = 60.0,
    ["aptar"] = 60.0,
    ["tec9belso"] = 60.0,
    ["tec9cso"] = 60.0,
    ["tec9tar"] = 60.0,
    ["weapon_vintagepistol"] = 60.0,
    ["vimarkolat"] = 60.0,
    ["viravasz"] = 60.0,
    ["vitar"] = 60.0,
    ["vivaz"] = 60.0,
    ["weapon_combatpdw"] = 60.0,
    ["cbcso"] = 60.0,
    ["cbmarkolat"] = 60.0,
    ["cbrravasz"] = 60.0,
    ["cbtarto"] = 60.0,
    ["pistolbelso"] = 60.0,
    ["pistolcso"] = 60.0,
    ["pistoltar"] = 60.0,
}

CraftAllowedJobs = {
    ["weapon_pistol"] = false,
    ["weapon_machinepistol"] = { "banda", "b2803ee2fa81a04fc333dd6d1e008d3414f588de", "bd82d20c8b77af4762525b1b8ee241ba09e4aa39" },
    ["weapon_assaultrifle"] = { "maffia", "b2803ee2fa81a04fc333dd6d1e008d3414f588de", "bd82d20c8b77af4762525b1b8ee241ba09e4aa39" },
    ["weapon_pumpshotgun"] = { "maffia", "b2803ee2fa81a04fc333dd6d1e008d3414f588de", "bd82d20c8b77af4762525b1b8ee241ba09e4aa39" },
    ["weapon_microsmg"] = { "banda", "b2803ee2fa81a04fc333dd6d1e008d3414f588de", "bd82d20c8b77af4762525b1b8ee241ba09e4aa39" },
    ["weapon_appistol"] = { "banda", "b2803ee2fa81a04fc333dd6d1e008d3414f588de", "bd82d20c8b77af4762525b1b8ee241ba09e4aa39" },
    ["apmarkolat"] = false,
    ["apravasz"] = false,
    ["apvaz"] = false,
    ["aptar"] = false,
    ["tec9belso"] = false,
    ["tec9cso"] = false,
    ["tec9tar"] = false,
    ["weapon_vintagepistol"] = { "banda", "b2803ee2fa81a04fc333dd6d1e008d3414f588de", "bd82d20c8b77af4762525b1b8ee241ba09e4aa39" },
    ["vimarkolat"] = false,
    ["viravasz"] = false,
    ["vitar"] = false,
    ["vivaz"] = false,
    ["weapon_combatpdw"] = { "banda", "b2803ee2fa81a04fc333dd6d1e008d3414f588de", "bd82d20c8b77af4762525b1b8ee241ba09e4aa39" },
    ["cbcso"] = false,
    ["cbmarkolat"] = false,
    ["cbrravasz"] = false,
    ["cbtarto"] = false,
    ["pistolbelso"] = false,
    ["pistolcso"] = false,
    ["pistoltar"] = false,
}

ExtraNeedItems = {
    ["weapon_pistol"] = "kiscraftkulcs",
    ["weapon_machinepistol"] = "kiscraftkulcs",
    ["weapon_assaultrifle"] = "nagycraftkulcs",
    ["weapon_pumpshotgun"] = "nagycraftkulcs",
    ["weapon_microsmg"] = "kiscraftkulcs",
    ["weapon_appistol"] = "kiscraftkulcs",
    ["apmarkolat"] = false,
    ["apravasz"] = false,
    ["apvaz"] = false,
    ["aptar"] = false,
    ["tec9belso"] = false,
    ["tec9cso"] = false,
    ["tec9tar"] = false,
    ["weapon_vintagepistol"] = "kiscraftkulcs",
    ["vimarkolat"] = false,
    ["viravasz"] = false,
    ["vitar"] = false,
    ["vivaz"] = false,
    ["weapon_combatpdw"] = "kiscraftkulcs",
    ["cbcso"] = false,
    ["cbmarkolat"] = false,
    ["cbrravasz"] = false,
    ["cbtarto"] = false,
    ["pistolbelso"] = false,
    ["pistolcso"] = false,
    ["pistoltar"] = false,
}

RecipeItems = {                          -- EZEK RECEPT ITEMEK, CSAK MEGMUTATJAK HOGY KELL BEPAKOLNI
    ["weapon_pistol"] = "recipe_pistol", -- fegyverterv2
    ["weapon_machinepistol"] = "fegyverterv3",
    ["weapon_assaultrifle"] = "fegyverterv4",
    ["weapon_pumpshotgun"] = "fegyverterv5",
    ["weapon_microsmg"] = "fegyverterv6",
    ["weapon_appistol"] = "fegyverterv7",
    ["apmarkolat"] = false,
    ["apravasz"] = false,
    ["apvaz"] = false,
    ["aptar"] = false,
    ["tec9belso"] = false,
    ["tec9cso"] = false,
    ["tec9tar"] = false,
    ["weapon_vintagepistol"] = false,
    ["vimarkolat"] = false,
    ["viravasz"] = false,
    ["vitar"] = false,
    ["vivaz"] = false,
    ["weapon_combatpdw"] = false,
    ["cbcso"] = false,
    ["cbmarkolat"] = false,
    ["cbrravasz"] = false,
    ["cbtarto"] = false,
    ["pistolbelso"] = false,
    ["pistolcso"] = false,
    ["pistoltar"] = false,
}
